<p>A few days before December the 1st, 2013, the U.S. Embassy in Mexico orders the censorship of the website 1Dmx.org. On December the 2nd, GoDaddy.com, a U.S. based company which provides Internet domains, takes down the site.</p>
<p>1Dmx.org is an informative website created on December the 2nd 2012 in order to document human rights violations and police abuse registered during Enrique Peña Nieto’s swearing as a president on December 1st. The site made technological resources available, which allowed people to organize and gather evidence on the Internet related to the events. The information gathered helped refuting the official version of the facts and was proof that the government had fabricated testimonies and false evidence against the people arrested on that day.</p>
<p>The documentation assembled by citizens confirmed that de Federal Police used rubber bullets. It also proofed that the projectile that killed the theater director and activist Juan Francisco Kuykendall, came from police forces and not from the demonstrators. Videos and pictures showed that the police acted in coordination with government paid rioters. The National Human Rights Commission still remains silent.</p>
<p>As a first email reply, GoDaddy.com argues that the site was taken down because of a violation of the terms of service. However, on the next day, in a second email, the company reveals that the real reason behind the suspension of the domain is that there is an undergoing law enforcement investigation. Without clarifying neither the authority behind this investigation nor its motives, GoDaddy.com says that for more information, one must contact a Homeland Security Investigations Special Agent at the U.S. Embassy in Mexico.</p>
<p>The Agent was contacted. However, he refused to give any information on the case, with an unjustifiable opacity. Given that the order to censor comes from the Embassy, we are inclined to presume that there is at least one authority of the Mexican government involved in de suspension of the domain. Thus, on December 24th, 2013, we filed an appeal on the grounds of unconstitutionality before the Eighth District Court on Administrative Matters. The judge orders the indicated authorities to hand in an inform justifying their participation. To the date, two of these authorities have not turned over the required information, missing the deadline defined by the judge.</p>
<p>In recent days, GoDaddy.com confirmed that the Mexican agency which requested the U.S. government to censor 1Dmx.org, was the Specialized Centre on Technological Response (CERT in Spanish). This is an agency of the Federal Police, which depends upon de Secretariat of the Interior since 2013. It is no coincidence that the two authorities that have not yet handed in the required information to the judge, are the Secretariat of the Interior and the National Security Commission.</p>
<p>We find it regrettable that the collaboration of the U.S. government with the Mexican government compromises freedom of speech in Mexico.</p>
<p>More than the return of the domain 1Dmx.org, we point out that our struggle is for freedom of speech. We will upload the content censored as many times as necessary. Until the domain is returned, the content will be available on http://op1d.mx</p>
<p>The censorship was executed by the Secretariat of the Interior through the National Security Commission. We hold, Commissioner Manuel Mondragón, responsible for censoring of the website 1Dmx.org. He is also responsible for the police operation of December the 1st, 2012.</p>
<p>We demand the Commissioner to explain in a statement why the agency on his command ordered the censorship of the website.</p>
<p>How many more websites has the Mexican government taken down? Why does the U.S. government collaborate on restraining the free expression of ideas in other countries? Who should be under investigation, the authorities that repress or the citizens that document and report those abuses? Prior censorship is a violation of human right and an unacceptable unconstitutional action, deeply related to authoritarian regimes.</p>
<p>The current Mexican government is stained by a systematic repression of freedom of speech. The police operation deployed during the swearing in of president Peña Nieto left a toll of: 99 arbitrary arrests, 6 documented cases of torture and one murder by the security forces. At least 58 journalists have been attacked in social rallies and six journalists have been murdered from December 1st 2012 to date. In just over a year, 267 people have been arrested during rallies, only in Mexico City. Today the only opposition allowed in Mexico, is the simulated opposition.</p>
<p>Censorship as a form of government reeks of the worst years of the PRI party, when the closure of newspapers and broadcasters, as well as the investigation of the political dissent was an everyday practice.</p>
<p>The wall imposed on the streets on December 1st, 2012 has come to the Internet. They can take down a site, but they cannot shut its voice. Censorship is an unacceptable violation of freedom of speech and must be investigated and punished. However, censorship also shows the power we have as citizens. Today cameras and information networks are our weapons against political authoritarianism. We call users, the media, and the citizens in general to defend the Internet as a free space, from which one can express, consult, and discuss ideas, both those that are against and for the government in turn. If censorship does not respect boarders, neither should freedom, information and solidarity. 1Dmx.org</p>