<p>Unos días antes del 1º de diciembre del 2013, la Embajada de Estados Unidos en México ordena la censura del sitio 1Dmx.org. El 2 de diciembre del mismo año, GoDaddy.com, la empresa proveedora de dominios en Internet, radicada en Estados Unidos, baja el sitio.</p>
<p>1Dmx.org es un sitio informativo que nació el 2 de diciembre del 2012 para documentar las violaciones a los derechos humanos y los abusos policiacos que se registraron durante la toma de protesta de Enrique Peña Nieto. El sitio puso a disposición de la ciudadanía recursos tecnológicos que permitieron organizar y concentrar las pruebas que circulaban en Internet. Información que desmintió la versión oficial y que demostró que el gobierno había fabricado testimonios y pruebas falsas contra los detenidos.</p>
<p>La documentación ciudadana también demostró que la Policía Federal utilizó balas de goma y que el proyectil que asesinó al director teatral y activista Juan Francisco Kuykendall Leal, provino de los cuerpos policiacos y no de los manifestantes. Los videos y fotografías mostraron que la policía actuó en coordinación con grupos de choque. Hechos sobre los que sigue sin pronunciarse la Comisión Nacional de Derechos Humanos.</p>
<p>En un primer correo, GoDaddy.com argumenta la violación de los términos del servicio, pero al día siguiente, revela que la verdadera razón para la suspensión es que existe una investigación policiaca en curso. Sin aclarar quién lleva a cabo la investigación o por qué motivos, la empresa notifica que para obtener más información, es necesario contactar a un Agente Especial de Seguridad Nacional de la embajada estadounidense en México.</p>
<p>Contactamos al Agente pero en una actitud de opacidad innecesaria e injustificable, éste se niega a dar cualquier información sobre el caso. Que la orden de censura provenga de la Embajada, permite suponer que hay cuando menos una dependencia del gobierno mexicano relacionada con la suspensión del dominio. Por lo tanto, el 24 de diciembre del 2013, interpusimos un amparo ante el Juzgado Octavo de Distrito en Materia Administrativa. El juez ordena a las autoridades señaladas, entregar un informe justificado sobre su participación. A la fecha, dos de éstas autoridades no han entregado la información solicitada, incumpliendo el plazo señalado por el juez.</p>
<p>En días recientes, la empresa GoDaddy confirmó que la agencia mexicana que solicitó al gobierno estadounidense la censura de 1Dmx.org, fue el Centro Especializado en Respuesta Tecnológica (CERT), una dependencia de la Policía Federal de la Comisión Nacional de Seguridad, que desde el 2013 depende de la Secretaría de Gobernación. La Comisión Nacional de Seguridad y la Secretaría de Gobernación son, además, las autoridades que no han entregado el informe justificado.</p>
<p>Nos parece lamentable que la colaboración del gobierno de Estados Unidos con el gobierno mexicano comprometa la libertad de expresión en México.</p>
<p>Más allá de la restitución del dominio 1dmx.org, advertimos que nuestra lucha es por la libertad de expresión. Subiremos a la red, todas las veces que sea necesario, el contenido censurado. Hasta que se restituya el dominio original, la información puede consultarse en http://op1d.mx</p>
<p>Señalamos como responsable de la censura de 1Dmx.org -que fue ejecutada por la Secretaría de Gobernación a través de la Comisión Nacional de Seguridad-, al comisionado Manuel Mondragón. Quien además es responsable del operativo del 1º de diciembre del 2012.</p>
<p>Exigimos un pronunciamiento del Comisionado donde explique por qué la agencia a su cargo, ordenó la censura del sitio.</p>
<p>¿Cuántas páginas más ha tirado el gobierno mexicano? ¿Por qué el gobierno estadounidense colabora para censurar la libre manifestación de las ideas en otros países? ¿Quiénes deberían estar bajo investigación, las autoridades que reprimen o la ciudadanía que documenta y denuncia esos abusos? La censura previa es una violación a los derechos humanos y un acto inconstitucional inaceptable, propio de los regímenes autoritarios.</p>
<p>El gobierno actual está marcado por la represión sistemática de la libertad de expresión. El operativo desplegado durante la toma de posesión de Peña Nieto, dejó como saldo; 99 detenciones arbitrarias, 6 casos de tortura documentados y una persona asesinada por las fuerzas del orden. Al menos 58 periodistas han sido agredidos en contextos de manifestaciones sociales y seis periodistas fueron asesinados en el periodo que va del 1º de diciembre del 2012 a la fecha. En poco más de un año, 267 personas han sido detenidas durante manifestaciones, sólo en el Distrito Federal. Hoy la única oposición permitida en México, es la oposición simulada.</p>
<p>La censura como forma de gobierno apesta a los peores años del PRI, cuando el cierre de periódicos y radiodifusoras, así como la investigación judicial de la disidencia política era una práctica habitual.</p>
<p>El cerco que impusieron en las calles el 1º de diciembre del 2012 ha llegado a Internet. Pueden bajar un sitio pero no pueden callar su voz. La censura es una violación a la libertad de expresión inadmisible que debe ser investigada y sancionada. Pero la censura también muestra el poder que tenemos como ciudadanos. Hoy las cámaras y redes de información, son nuestras armas contra el autoritarismo y la soberbia del poder. Llamamos a los usuarios, a los medios de comunicación y a la ciudadanía en general a defender Internet como un espacio libre, desde dónde se puedan expresar, consultar y discutir ideas, tanto afines como críticas de los gobiernos. Si la censura no respeta fronteras, que la libertad, la información y la solidaridad tampoco lo hagan. 1Dmx.org</p>